# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/testDMA_wrapper.xdc

# Block Designs: bd/testDMA/testDMA.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA || ORIG_REF_NAME==testDMA}]

# IP: bd/testDMA/ip/testDMA_processing_system7_0_0/testDMA_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_processing_system7_0_0 || ORIG_REF_NAME==testDMA_processing_system7_0_0}]

# IP: bd/testDMA/ip/testDMA_def_stream_0_0/testDMA_def_stream_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_def_stream_0_0 || ORIG_REF_NAME==testDMA_def_stream_0_0}]

# IP: bd/testDMA/ip/testDMA_axi_dma_0_0/testDMA_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_axi_dma_0_0 || ORIG_REF_NAME==testDMA_axi_dma_0_0}]

# IP: bd/testDMA/ip/testDMA_processing_system7_0_axi_periph_0/testDMA_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==testDMA_processing_system7_0_axi_periph_0}]

# IP: bd/testDMA/ip/testDMA_proc_sys_reset_0/testDMA_proc_sys_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_proc_sys_reset_0 || ORIG_REF_NAME==testDMA_proc_sys_reset_0}]

# IP: bd/testDMA/ip/testDMA_xbar_1/testDMA_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_xbar_1 || ORIG_REF_NAME==testDMA_xbar_1}]

# IP: bd/testDMA/ip/testDMA_axi_mem_intercon_1/testDMA_axi_mem_intercon_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_axi_mem_intercon_1 || ORIG_REF_NAME==testDMA_axi_mem_intercon_1}]

# IP: bd/testDMA/ip/testDMA_xbar_3/testDMA_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_xbar_3 || ORIG_REF_NAME==testDMA_xbar_3}]

# IP: bd/testDMA/ip/testDMA_axis_data_fifo_0_1/testDMA_axis_data_fifo_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_axis_data_fifo_0_1 || ORIG_REF_NAME==testDMA_axis_data_fifo_0_1}]

# IP: bd/testDMA/ip/testDMA_ADC_emul_0_9/testDMA_ADC_emul_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_ADC_emul_0_9 || ORIG_REF_NAME==testDMA_ADC_emul_0_9}]

# IP: bd/testDMA/ip/testDMA_auto_pc_573_0/testDMA_auto_pc_573.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_573 || ORIG_REF_NAME==testDMA_auto_pc_573}]

# IP: bd/testDMA/ip/testDMA_auto_ds_469_0/testDMA_auto_ds_469.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_ds_469 || ORIG_REF_NAME==testDMA_auto_ds_469}]

# IP: bd/testDMA/ip/testDMA_auto_pc_574_0/testDMA_auto_pc_574.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_574 || ORIG_REF_NAME==testDMA_auto_pc_574}]

# IP: bd/testDMA/ip/testDMA_auto_ds_470_0/testDMA_auto_ds_470.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_ds_470 || ORIG_REF_NAME==testDMA_auto_ds_470}]

# IP: bd/testDMA/ip/testDMA_auto_pc_575_0/testDMA_auto_pc_575.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_575 || ORIG_REF_NAME==testDMA_auto_pc_575}]

# IP: bd/testDMA/ip/testDMA_auto_pc_576_0/testDMA_auto_pc_576.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_576 || ORIG_REF_NAME==testDMA_auto_pc_576}]

# IP: bd/testDMA/ip/testDMA_auto_pc_577_0/testDMA_auto_pc_577.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_577 || ORIG_REF_NAME==testDMA_auto_pc_577}]

# IP: bd/testDMA/ip/testDMA_auto_us_472_0/testDMA_auto_us_472.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_us_472 || ORIG_REF_NAME==testDMA_auto_us_472}]

# IP: bd/testDMA/ip/testDMA_auto_pc_578_0/testDMA_auto_pc_578.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_578 || ORIG_REF_NAME==testDMA_auto_pc_578}]

# IP: bd/testDMA/ip/testDMA_auto_us_473_0/testDMA_auto_us_473.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_us_473 || ORIG_REF_NAME==testDMA_auto_us_473}]

# IP: bd/testDMA/ip/testDMA_auto_ds_682_0/testDMA_auto_ds_682.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_ds_682 || ORIG_REF_NAME==testDMA_auto_ds_682}]

# IP: bd/testDMA/ip/testDMA_auto_ds_683_0/testDMA_auto_ds_683.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_ds_683 || ORIG_REF_NAME==testDMA_auto_ds_683}]

# IP: bd/testDMA/ip/testDMA_auto_us_685_0/testDMA_auto_us_685.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_us_685 || ORIG_REF_NAME==testDMA_auto_us_685}]

# IP: bd/testDMA/ip/testDMA_axi_data_fifo_0_2/testDMA_axi_data_fifo_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_axi_data_fifo_0_2 || ORIG_REF_NAME==testDMA_axi_data_fifo_0_2}]

# IP: bd/testDMA/ip/testDMA_init_dma_1_0/testDMA_init_dma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_init_dma_1_0 || ORIG_REF_NAME==testDMA_init_dma_1_0}]

# IP: bd/testDMA/ip/testDMA_reg_status_0_1/testDMA_reg_status_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_reg_status_0_1 || ORIG_REF_NAME==testDMA_reg_status_0_1}]

# IP: bd/testDMA/ip/testDMA_auto_ds_1265/testDMA_auto_ds_1265.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_ds_1265 || ORIG_REF_NAME==testDMA_auto_ds_1265}]

# IP: bd/testDMA/ip/testDMA_auto_pc_1375/testDMA_auto_pc_1375.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_1375 || ORIG_REF_NAME==testDMA_auto_pc_1375}]

# IP: bd/testDMA/ip/testDMA_auto_ds_1266/testDMA_auto_ds_1266.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_ds_1266 || ORIG_REF_NAME==testDMA_auto_ds_1266}]

# IP: bd/testDMA/ip/testDMA_auto_pc_1376/testDMA_auto_pc_1376.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_1376 || ORIG_REF_NAME==testDMA_auto_pc_1376}]

# IP: bd/testDMA/ip/testDMA_auto_ds_1267/testDMA_auto_ds_1267.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_ds_1267 || ORIG_REF_NAME==testDMA_auto_ds_1267}]

# IP: bd/testDMA/ip/testDMA_auto_pc_1377/testDMA_auto_pc_1377.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_1377 || ORIG_REF_NAME==testDMA_auto_pc_1377}]

# IP: bd/testDMA/ip/testDMA_auto_pc_1378/testDMA_auto_pc_1378.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_1378 || ORIG_REF_NAME==testDMA_auto_pc_1378}]

# IP: bd/testDMA/ip/testDMA_auto_us_1268/testDMA_auto_us_1268.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_us_1268 || ORIG_REF_NAME==testDMA_auto_us_1268}]

# IP: bd/testDMA/ip/testDMA_auto_pc_1379/testDMA_auto_pc_1379.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_1379 || ORIG_REF_NAME==testDMA_auto_pc_1379}]

# IP: bd/testDMA/ip/testDMA_auto_us_1269/testDMA_auto_us_1269.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_us_1269 || ORIG_REF_NAME==testDMA_auto_us_1269}]

# IP: bd/testDMA/ip/testDMA_auto_pc_1380/testDMA_auto_pc_1380.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_1380 || ORIG_REF_NAME==testDMA_auto_pc_1380}]

# IP: bd/testDMA/ip/testDMA_auto_us_1270/testDMA_auto_us_1270.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_us_1270 || ORIG_REF_NAME==testDMA_auto_us_1270}]

# XDC: bd/testDMA/ip/testDMA_processing_system7_0_0/testDMA_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_processing_system7_0_0 || ORIG_REF_NAME==testDMA_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/testDMA/ip/testDMA_axi_dma_0_0/testDMA_axi_dma_0_0_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_axi_dma_0_0/testDMA_axi_dma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_axi_dma_0_0 || ORIG_REF_NAME==testDMA_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/testDMA/ip/testDMA_axi_dma_0_0/testDMA_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_axi_dma_0_0 || ORIG_REF_NAME==testDMA_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/testDMA/ip/testDMA_proc_sys_reset_0/testDMA_proc_sys_reset_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_proc_sys_reset_0 || ORIG_REF_NAME==testDMA_proc_sys_reset_0}] {/U0 }]/U0 ]]

# XDC: bd/testDMA/ip/testDMA_proc_sys_reset_0/testDMA_proc_sys_reset_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_proc_sys_reset_0 || ORIG_REF_NAME==testDMA_proc_sys_reset_0}] {/U0 }]/U0 ]]

# XDC: bd/testDMA/ip/testDMA_proc_sys_reset_0/testDMA_proc_sys_reset_0_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_xbar_1/testDMA_xbar_1_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_xbar_3/testDMA_xbar_3_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_axis_data_fifo_0_1/testDMA_axis_data_fifo_0_1_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_axis_data_fifo_0_1/testDMA_axis_data_fifo_0_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_axis_data_fifo_0_1 || ORIG_REF_NAME==testDMA_axis_data_fifo_0_1}] {/inst }]/inst ]]

# XDC: bd/testDMA/ip/testDMA_auto_ds_1265/testDMA_auto_ds_1265_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_ds_1265/testDMA_auto_ds_1265_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_auto_ds_1265 || ORIG_REF_NAME==testDMA_auto_ds_1265}] {/inst }]/inst ]]

# XDC: bd/testDMA/ip/testDMA_auto_pc_1375/testDMA_auto_pc_1375_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_ds_1266/testDMA_auto_ds_1266_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_ds_1266/testDMA_auto_ds_1266_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_auto_ds_1266 || ORIG_REF_NAME==testDMA_auto_ds_1266}] {/inst }]/inst ]]

# XDC: bd/testDMA/ip/testDMA_auto_pc_1376/testDMA_auto_pc_1376_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_ds_1267/testDMA_auto_ds_1267_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_ds_1267/testDMA_auto_ds_1267_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_auto_ds_1267 || ORIG_REF_NAME==testDMA_auto_ds_1267}] {/inst }]/inst ]]

# XDC: bd/testDMA/ip/testDMA_auto_pc_1377/testDMA_auto_pc_1377_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_pc_1378/testDMA_auto_pc_1378_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_us_1268/testDMA_auto_us_1268_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_us_1268/testDMA_auto_us_1268_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_auto_us_1268 || ORIG_REF_NAME==testDMA_auto_us_1268}] {/inst }]/inst ]]

# XDC: bd/testDMA/ip/testDMA_auto_pc_1379/testDMA_auto_pc_1379_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_us_1269/testDMA_auto_us_1269_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_us_1269/testDMA_auto_us_1269_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_auto_us_1269 || ORIG_REF_NAME==testDMA_auto_us_1269}] {/inst }]/inst ]]

# XDC: bd/testDMA/ip/testDMA_auto_pc_1380/testDMA_auto_pc_1380_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_us_1270/testDMA_auto_us_1270_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_us_1270/testDMA_auto_us_1270_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_auto_us_1270 || ORIG_REF_NAME==testDMA_auto_us_1270}] {/inst }]/inst ]]

# XDC: bd/testDMA/testDMA_ooc.xdc
