# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/testDMA_wrapper.xdc

# Block Designs: bd/testDMA/testDMA.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA || ORIG_REF_NAME==testDMA}]

# IP: bd/testDMA/ip/testDMA_processing_system7_0_0/testDMA_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_processing_system7_0_0 || ORIG_REF_NAME==testDMA_processing_system7_0_0}]

# IP: bd/testDMA/ip/testDMA_def_stream_0_0/testDMA_def_stream_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_def_stream_0_0 || ORIG_REF_NAME==testDMA_def_stream_0_0}]

# IP: bd/testDMA/ip/testDMA_axi_dma_0_0/testDMA_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_axi_dma_0_0 || ORIG_REF_NAME==testDMA_axi_dma_0_0}]

# IP: bd/testDMA/ip/testDMA_processing_system7_0_axi_periph_0/testDMA_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==testDMA_processing_system7_0_axi_periph_0}]

# IP: bd/testDMA/ip/testDMA_proc_sys_reset_0/testDMA_proc_sys_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_proc_sys_reset_0 || ORIG_REF_NAME==testDMA_proc_sys_reset_0}]

# IP: bd/testDMA/ip/testDMA_xbar_1/testDMA_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_xbar_1 || ORIG_REF_NAME==testDMA_xbar_1}]

# IP: bd/testDMA/ip/testDMA_axi_mem_intercon_1/testDMA_axi_mem_intercon_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_axi_mem_intercon_1 || ORIG_REF_NAME==testDMA_axi_mem_intercon_1}]

# IP: bd/testDMA/ip/testDMA_xbar_3/testDMA_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_xbar_3 || ORIG_REF_NAME==testDMA_xbar_3}]

# IP: bd/testDMA/ip/testDMA_axis_data_fifo_0_1/testDMA_axis_data_fifo_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_axis_data_fifo_0_1 || ORIG_REF_NAME==testDMA_axis_data_fifo_0_1}]

# IP: bd/testDMA/ip/testDMA_ADC_emul_0_9/testDMA_ADC_emul_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_ADC_emul_0_9 || ORIG_REF_NAME==testDMA_ADC_emul_0_9}]

# IP: bd/testDMA/ip/testDMA_auto_pc_573_0/testDMA_auto_pc_573.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_573 || ORIG_REF_NAME==testDMA_auto_pc_573}]

# IP: bd/testDMA/ip/testDMA_auto_ds_469_0/testDMA_auto_ds_469.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_ds_469 || ORIG_REF_NAME==testDMA_auto_ds_469}]

# IP: bd/testDMA/ip/testDMA_auto_pc_574_0/testDMA_auto_pc_574.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_574 || ORIG_REF_NAME==testDMA_auto_pc_574}]

# IP: bd/testDMA/ip/testDMA_auto_ds_470_0/testDMA_auto_ds_470.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_ds_470 || ORIG_REF_NAME==testDMA_auto_ds_470}]

# IP: bd/testDMA/ip/testDMA_auto_pc_575_0/testDMA_auto_pc_575.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_575 || ORIG_REF_NAME==testDMA_auto_pc_575}]

# IP: bd/testDMA/ip/testDMA_auto_pc_576_0/testDMA_auto_pc_576.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_576 || ORIG_REF_NAME==testDMA_auto_pc_576}]

# IP: bd/testDMA/ip/testDMA_auto_pc_577_0/testDMA_auto_pc_577.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_577 || ORIG_REF_NAME==testDMA_auto_pc_577}]

# IP: bd/testDMA/ip/testDMA_auto_us_472_0/testDMA_auto_us_472.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_us_472 || ORIG_REF_NAME==testDMA_auto_us_472}]

# IP: bd/testDMA/ip/testDMA_auto_pc_578_0/testDMA_auto_pc_578.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_578 || ORIG_REF_NAME==testDMA_auto_pc_578}]

# IP: bd/testDMA/ip/testDMA_auto_us_473_0/testDMA_auto_us_473.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_us_473 || ORIG_REF_NAME==testDMA_auto_us_473}]

# IP: bd/testDMA/ip/testDMA_auto_ds_682_0/testDMA_auto_ds_682.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_ds_682 || ORIG_REF_NAME==testDMA_auto_ds_682}]

# IP: bd/testDMA/ip/testDMA_auto_ds_683_0/testDMA_auto_ds_683.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_ds_683 || ORIG_REF_NAME==testDMA_auto_ds_683}]

# IP: bd/testDMA/ip/testDMA_auto_us_685_0/testDMA_auto_us_685.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_us_685 || ORIG_REF_NAME==testDMA_auto_us_685}]

# IP: bd/testDMA/ip/testDMA_init_dma_1_0/testDMA_init_dma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_init_dma_1_0 || ORIG_REF_NAME==testDMA_init_dma_1_0}]

# IP: bd/testDMA/ip/testDMA_auto_ds_1415/testDMA_auto_ds_1415.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_ds_1415 || ORIG_REF_NAME==testDMA_auto_ds_1415}]

# IP: bd/testDMA/ip/testDMA_auto_pc_1525/testDMA_auto_pc_1525.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_1525 || ORIG_REF_NAME==testDMA_auto_pc_1525}]

# IP: bd/testDMA/ip/testDMA_auto_ds_1416/testDMA_auto_ds_1416.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_ds_1416 || ORIG_REF_NAME==testDMA_auto_ds_1416}]

# IP: bd/testDMA/ip/testDMA_auto_pc_1526/testDMA_auto_pc_1526.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_1526 || ORIG_REF_NAME==testDMA_auto_pc_1526}]

# IP: bd/testDMA/ip/testDMA_auto_ds_1417/testDMA_auto_ds_1417.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_ds_1417 || ORIG_REF_NAME==testDMA_auto_ds_1417}]

# IP: bd/testDMA/ip/testDMA_auto_pc_1527/testDMA_auto_pc_1527.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_1527 || ORIG_REF_NAME==testDMA_auto_pc_1527}]

# IP: bd/testDMA/ip/testDMA_auto_pc_1528/testDMA_auto_pc_1528.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_1528 || ORIG_REF_NAME==testDMA_auto_pc_1528}]

# IP: bd/testDMA/ip/testDMA_auto_us_1418/testDMA_auto_us_1418.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_us_1418 || ORIG_REF_NAME==testDMA_auto_us_1418}]

# IP: bd/testDMA/ip/testDMA_auto_pc_1529/testDMA_auto_pc_1529.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_1529 || ORIG_REF_NAME==testDMA_auto_pc_1529}]

# IP: bd/testDMA/ip/testDMA_auto_us_1419/testDMA_auto_us_1419.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_us_1419 || ORIG_REF_NAME==testDMA_auto_us_1419}]

# IP: bd/testDMA/ip/testDMA_auto_pc_1530/testDMA_auto_pc_1530.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_1530 || ORIG_REF_NAME==testDMA_auto_pc_1530}]

# IP: bd/testDMA/ip/testDMA_auto_us_1420/testDMA_auto_us_1420.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_us_1420 || ORIG_REF_NAME==testDMA_auto_us_1420}]

# XDC: bd/testDMA/ip/testDMA_processing_system7_0_0/testDMA_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_processing_system7_0_0 || ORIG_REF_NAME==testDMA_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/testDMA/ip/testDMA_axi_dma_0_0/testDMA_axi_dma_0_0_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_axi_dma_0_0/testDMA_axi_dma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_axi_dma_0_0 || ORIG_REF_NAME==testDMA_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/testDMA/ip/testDMA_axi_dma_0_0/testDMA_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_axi_dma_0_0 || ORIG_REF_NAME==testDMA_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/testDMA/ip/testDMA_proc_sys_reset_0/testDMA_proc_sys_reset_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_proc_sys_reset_0 || ORIG_REF_NAME==testDMA_proc_sys_reset_0}] {/U0 }]/U0 ]]

# XDC: bd/testDMA/ip/testDMA_proc_sys_reset_0/testDMA_proc_sys_reset_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_proc_sys_reset_0 || ORIG_REF_NAME==testDMA_proc_sys_reset_0}] {/U0 }]/U0 ]]

# XDC: bd/testDMA/ip/testDMA_proc_sys_reset_0/testDMA_proc_sys_reset_0_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_xbar_1/testDMA_xbar_1_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_xbar_3/testDMA_xbar_3_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_axis_data_fifo_0_1/testDMA_axis_data_fifo_0_1_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_axis_data_fifo_0_1/testDMA_axis_data_fifo_0_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_axis_data_fifo_0_1 || ORIG_REF_NAME==testDMA_axis_data_fifo_0_1}] {/inst }]/inst ]]

# XDC: bd/testDMA/ip/testDMA_auto_ds_1415/testDMA_auto_ds_1415_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_ds_1415/testDMA_auto_ds_1415_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_auto_ds_1415 || ORIG_REF_NAME==testDMA_auto_ds_1415}] {/inst }]/inst ]]

# XDC: bd/testDMA/ip/testDMA_auto_pc_1525/testDMA_auto_pc_1525_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_ds_1416/testDMA_auto_ds_1416_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_ds_1416/testDMA_auto_ds_1416_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_auto_ds_1416 || ORIG_REF_NAME==testDMA_auto_ds_1416}] {/inst }]/inst ]]

# XDC: bd/testDMA/ip/testDMA_auto_pc_1526/testDMA_auto_pc_1526_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_ds_1417/testDMA_auto_ds_1417_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_ds_1417/testDMA_auto_ds_1417_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_auto_ds_1417 || ORIG_REF_NAME==testDMA_auto_ds_1417}] {/inst }]/inst ]]

# XDC: bd/testDMA/ip/testDMA_auto_pc_1527/testDMA_auto_pc_1527_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_pc_1528/testDMA_auto_pc_1528_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_us_1418/testDMA_auto_us_1418_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_us_1418/testDMA_auto_us_1418_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_auto_us_1418 || ORIG_REF_NAME==testDMA_auto_us_1418}] {/inst }]/inst ]]

# XDC: bd/testDMA/ip/testDMA_auto_pc_1529/testDMA_auto_pc_1529_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_us_1419/testDMA_auto_us_1419_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_us_1419/testDMA_auto_us_1419_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_auto_us_1419 || ORIG_REF_NAME==testDMA_auto_us_1419}] {/inst }]/inst ]]

# XDC: bd/testDMA/ip/testDMA_auto_pc_1530/testDMA_auto_pc_1530_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_us_1420/testDMA_auto_us_1420_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_us_1420/testDMA_auto_us_1420_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_auto_us_1420 || ORIG_REF_NAME==testDMA_auto_us_1420}] {/inst }]/inst ]]

# XDC: bd/testDMA/testDMA_ooc.xdc
