# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/testDMA_wrapper.xdc

# Block Designs: bd/testDMA/testDMA.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA || ORIG_REF_NAME==testDMA}]

# IP: bd/testDMA/ip/testDMA_processing_system7_0_0/testDMA_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_processing_system7_0_0 || ORIG_REF_NAME==testDMA_processing_system7_0_0}]

# IP: bd/testDMA/ip/testDMA_def_stream_0_0/testDMA_def_stream_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_def_stream_0_0 || ORIG_REF_NAME==testDMA_def_stream_0_0}]

# IP: bd/testDMA/ip/testDMA_axi_dma_0_0/testDMA_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_axi_dma_0_0 || ORIG_REF_NAME==testDMA_axi_dma_0_0}]

# IP: bd/testDMA/ip/testDMA_processing_system7_0_axi_periph_0/testDMA_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==testDMA_processing_system7_0_axi_periph_0}]

# IP: bd/testDMA/ip/testDMA_proc_sys_reset_0/testDMA_proc_sys_reset_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_proc_sys_reset_0 || ORIG_REF_NAME==testDMA_proc_sys_reset_0}]

# IP: bd/testDMA/ip/testDMA_xbar_1/testDMA_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_xbar_1 || ORIG_REF_NAME==testDMA_xbar_1}]

# IP: bd/testDMA/ip/testDMA_axi_mem_intercon_1/testDMA_axi_mem_intercon_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_axi_mem_intercon_1 || ORIG_REF_NAME==testDMA_axi_mem_intercon_1}]

# IP: bd/testDMA/ip/testDMA_xbar_3/testDMA_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_xbar_3 || ORIG_REF_NAME==testDMA_xbar_3}]

# IP: bd/testDMA/ip/testDMA_init_dma_v4_0_1/testDMA_init_dma_v4_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_init_dma_v4_0_1 || ORIG_REF_NAME==testDMA_init_dma_v4_0_1}]

# IP: bd/testDMA/ip/testDMA_axis_data_fifo_0_1/testDMA_axis_data_fifo_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_axis_data_fifo_0_1 || ORIG_REF_NAME==testDMA_axis_data_fifo_0_1}]

# IP: bd/testDMA/ip/testDMA_ADC_emul_0_9/testDMA_ADC_emul_0_9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_ADC_emul_0_9 || ORIG_REF_NAME==testDMA_ADC_emul_0_9}]

# IP: bd/testDMA/ip/testDMA_auto_ds_408/testDMA_auto_ds_408.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_ds_408 || ORIG_REF_NAME==testDMA_auto_ds_408}]

# IP: bd/testDMA/ip/testDMA_auto_pc_513/testDMA_auto_pc_513.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_513 || ORIG_REF_NAME==testDMA_auto_pc_513}]

# IP: bd/testDMA/ip/testDMA_auto_ds_409/testDMA_auto_ds_409.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_ds_409 || ORIG_REF_NAME==testDMA_auto_ds_409}]

# IP: bd/testDMA/ip/testDMA_auto_pc_514/testDMA_auto_pc_514.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_514 || ORIG_REF_NAME==testDMA_auto_pc_514}]

# IP: bd/testDMA/ip/testDMA_auto_ds_410/testDMA_auto_ds_410.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_ds_410 || ORIG_REF_NAME==testDMA_auto_ds_410}]

# IP: bd/testDMA/ip/testDMA_auto_pc_515/testDMA_auto_pc_515.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_515 || ORIG_REF_NAME==testDMA_auto_pc_515}]

# IP: bd/testDMA/ip/testDMA_auto_pc_516/testDMA_auto_pc_516.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_516 || ORIG_REF_NAME==testDMA_auto_pc_516}]

# IP: bd/testDMA/ip/testDMA_auto_us_411/testDMA_auto_us_411.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_us_411 || ORIG_REF_NAME==testDMA_auto_us_411}]

# IP: bd/testDMA/ip/testDMA_auto_pc_517/testDMA_auto_pc_517.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_517 || ORIG_REF_NAME==testDMA_auto_pc_517}]

# IP: bd/testDMA/ip/testDMA_auto_us_412/testDMA_auto_us_412.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_us_412 || ORIG_REF_NAME==testDMA_auto_us_412}]

# IP: bd/testDMA/ip/testDMA_auto_pc_518/testDMA_auto_pc_518.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_pc_518 || ORIG_REF_NAME==testDMA_auto_pc_518}]

# IP: bd/testDMA/ip/testDMA_auto_us_413/testDMA_auto_us_413.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==testDMA_auto_us_413 || ORIG_REF_NAME==testDMA_auto_us_413}]

# XDC: bd/testDMA/ip/testDMA_processing_system7_0_0/testDMA_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_processing_system7_0_0 || ORIG_REF_NAME==testDMA_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/testDMA/ip/testDMA_axi_dma_0_0/testDMA_axi_dma_0_0_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_axi_dma_0_0/testDMA_axi_dma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_axi_dma_0_0 || ORIG_REF_NAME==testDMA_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/testDMA/ip/testDMA_axi_dma_0_0/testDMA_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_axi_dma_0_0 || ORIG_REF_NAME==testDMA_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/testDMA/ip/testDMA_proc_sys_reset_0/testDMA_proc_sys_reset_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_proc_sys_reset_0 || ORIG_REF_NAME==testDMA_proc_sys_reset_0}] {/U0 }]/U0 ]]

# XDC: bd/testDMA/ip/testDMA_proc_sys_reset_0/testDMA_proc_sys_reset_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_proc_sys_reset_0 || ORIG_REF_NAME==testDMA_proc_sys_reset_0}] {/U0 }]/U0 ]]

# XDC: bd/testDMA/ip/testDMA_proc_sys_reset_0/testDMA_proc_sys_reset_0_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_xbar_1/testDMA_xbar_1_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_xbar_3/testDMA_xbar_3_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_axis_data_fifo_0_1/testDMA_axis_data_fifo_0_1_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_axis_data_fifo_0_1/testDMA_axis_data_fifo_0_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_axis_data_fifo_0_1 || ORIG_REF_NAME==testDMA_axis_data_fifo_0_1}] {/inst }]/inst ]]

# XDC: bd/testDMA/ip/testDMA_auto_ds_408/testDMA_auto_ds_408_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_ds_408/testDMA_auto_ds_408_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_auto_ds_408 || ORIG_REF_NAME==testDMA_auto_ds_408}] {/inst }]/inst ]]

# XDC: bd/testDMA/ip/testDMA_auto_pc_513/testDMA_auto_pc_513_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_ds_409/testDMA_auto_ds_409_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_ds_409/testDMA_auto_ds_409_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_auto_ds_409 || ORIG_REF_NAME==testDMA_auto_ds_409}] {/inst }]/inst ]]

# XDC: bd/testDMA/ip/testDMA_auto_pc_514/testDMA_auto_pc_514_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_ds_410/testDMA_auto_ds_410_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_ds_410/testDMA_auto_ds_410_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_auto_ds_410 || ORIG_REF_NAME==testDMA_auto_ds_410}] {/inst }]/inst ]]

# XDC: bd/testDMA/ip/testDMA_auto_pc_515/testDMA_auto_pc_515_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_pc_516/testDMA_auto_pc_516_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_us_411/testDMA_auto_us_411_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_us_411/testDMA_auto_us_411_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_auto_us_411 || ORIG_REF_NAME==testDMA_auto_us_411}] {/inst }]/inst ]]

# XDC: bd/testDMA/ip/testDMA_auto_pc_517/testDMA_auto_pc_517_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_us_412/testDMA_auto_us_412_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_us_412/testDMA_auto_us_412_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_auto_us_412 || ORIG_REF_NAME==testDMA_auto_us_412}] {/inst }]/inst ]]

# XDC: bd/testDMA/ip/testDMA_auto_pc_518/testDMA_auto_pc_518_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_us_413/testDMA_auto_us_413_ooc.xdc

# XDC: bd/testDMA/ip/testDMA_auto_us_413/testDMA_auto_us_413_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==testDMA_auto_us_413 || ORIG_REF_NAME==testDMA_auto_us_413}] {/inst }]/inst ]]

# XDC: bd/testDMA/testDMA_ooc.xdc
