set_property PACKAGE_PIN T22 [get_ports LD0]
set_property PACKAGE_PIN T21 [get_ports LD1]
set_property PACKAGE_PIN U22 [get_ports LD2]
set_property PACKAGE_PIN U21 [get_ports LD3]
set_property PACKAGE_PIN V22 [get_ports LD4]
set_property PACKAGE_PIN W22 [get_ports LD5]
set_property PACKAGE_PIN U19 [get_ports LD6]
set_property PACKAGE_PIN U14 [get_ports LD7]
set_property IOSTANDARD LVCMOS25 [get_ports LD0]
set_property IOSTANDARD LVCMOS25 [get_ports LD1]
set_property IOSTANDARD LVCMOS25 [get_ports LD2]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[31]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[30]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[29]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[28]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[27]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[26]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[25]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[24]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[23]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[22]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[21]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[20]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[19]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[18]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[17]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[16]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[15]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[14]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[13]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[12]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {LD3[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports LD4]
set_property IOSTANDARD LVCMOS25 [get_ports LD5]
set_property IOSTANDARD LVCMOS25 [get_ports LD6]
set_property IOSTANDARD LVCMOS25 [get_ports LD7]


set_property PACKAGE_PIN Y11 [get_ports {JA1[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {JA1[0]}]

set_property PACKAGE_PIN L18 [get_ports clkp]
set_property PACKAGE_PIN L19 [get_ports clkn]
make_diff_pair_ports adcdp[0] adcdn[0]
make_diff_pair_ports adcdp[1] adcdn[1]
make_diff_pair_ports adcdp[2] adcdn[2]
make_diff_pair_ports adcdp[3] adcdn[3]
make_diff_pair_ports adcdp[4] adcdn[4]
make_diff_pair_ports adcdp[5] adcdn[5]
make_diff_pair_ports adcdp[6] adcdn[6]
make_diff_pair_ports adcdp[7] adcdn[7]
set_property IOSTANDARD LVDS_25 [get_ports clkp]
set_property IOSTANDARD LVDS_25 [get_ports {adcdp[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {adcdp[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {adcdp[2]}]
set_property IOSTANDARD LVDS_25 [get_ports {adcdp[3]}]
set_property IOSTANDARD LVDS_25 [get_ports {adcdp[4]}]
set_property IOSTANDARD LVDS_25 [get_ports {adcdp[5]}]
set_property IOSTANDARD LVDS_25 [get_ports {adcdp[6]}]
set_property IOSTANDARD LVDS_25 [get_ports {adcdp[7]}]
set_property LOC ILOGIC_X1Y74 [get_cells {testDMA_i/ADC_emul_0/inst/g_adc_if[0].i_data_ddr}]
set_property LOC IDELAY_X1Y74 [get_cells {testDMA_i/ADC_emul_0/inst/g_adc_if[0].i_data_idelay}]
set_property PACKAGE_PIN M19 [get_ports {adcdp[0]}]
set_property PACKAGE_PIN M20 [get_ports {adcdn[0]}]
set_property LOC ILOGIC_X1Y72 [get_cells {testDMA_i/ADC_emul_0/inst/g_adc_if[1].i_data_ddr}]
set_property LOC IDELAY_X1Y72 [get_cells {testDMA_i/ADC_emul_0/inst/g_adc_if[1].i_data_idelay}]
set_property PACKAGE_PIN N19 [get_ports {adcdp[1]}]
set_property PACKAGE_PIN N20 [get_ports {adcdn[1]}]
set_property LOC ILOGIC_X1Y60 [get_cells {testDMA_i/ADC_emul_0/inst/g_adc_if[2].i_data_ddr}]
set_property LOC IDELAY_X1Y60 [get_cells {testDMA_i/ADC_emul_0/inst/g_adc_if[2].i_data_idelay}]
set_property PACKAGE_PIN P17 [get_ports {adcdp[2]}]
set_property PACKAGE_PIN P18 [get_ports {adcdn[2]}]
set_property LOC ILOGIC_X1Y68 [get_cells {testDMA_i/ADC_emul_0/inst/g_adc_if[3].i_data_ddr}]
set_property LOC IDELAY_X1Y68 [get_cells {testDMA_i/ADC_emul_0/inst/g_adc_if[3].i_data_idelay}]
set_property PACKAGE_PIN N22 [get_ports {adcdp[3]}]
set_property PACKAGE_PIN P22 [get_ports {adcdn[3]}]
set_property LOC IDELAY_X1Y70 [get_cells {testDMA_i/ADC_emul_0/inst/g_adc_if[4].i_data_idelay}]
set_property LOC ILOGIC_X1Y70 [get_cells {testDMA_i/ADC_emul_0/inst/g_adc_if[4].i_data_ddr}]
set_property PACKAGE_PIN M21 [get_ports {adcdp[4]}]
set_property PACKAGE_PIN M22 [get_ports {adcdn[4]}]
set_property LOC IDELAY_X1Y86 [get_cells {testDMA_i/ADC_emul_0/inst/g_adc_if[5].i_data_idelay}]
set_property LOC ILOGIC_X1Y86 [get_cells {testDMA_i/ADC_emul_0/inst/g_adc_if[5].i_data_ddr}]
set_property PACKAGE_PIN J18 [get_ports {adcdp[5]}]
set_property PACKAGE_PIN K18 [get_ports {adcdn[5]}]
set_property LOC IDELAY_X1Y80 [get_cells {testDMA_i/ADC_emul_0/inst/g_adc_if[6].i_data_idelay}]
set_property LOC ILOGIC_X1Y80 [get_cells {testDMA_i/ADC_emul_0/inst/g_adc_if[6].i_data_ddr}]
set_property PACKAGE_PIN L21 [get_ports {adcdp[6]}]
set_property PACKAGE_PIN L22 [get_ports {adcdn[6]}]
set_property LOC IDELAY_X1Y58 [get_cells {testDMA_i/ADC_emul_0/inst/g_adc_if[7].i_data_idelay}]
set_property LOC ILOGIC_X1Y58 [get_cells {testDMA_i/ADC_emul_0/inst/g_adc_if[7].i_data_ddr}]
set_property PACKAGE_PIN T16 [get_ports {adcdp[7]}]
set_property PACKAGE_PIN T17 [get_ports {adcdn[7]}]

set_property LOC IDELAY_X1Y84 [get_cells testDMA_i/ADC_emul_0/inst/i_or_idelay]
set_property LOC ILOGIC_X1Y84 [get_cells testDMA_i/ADC_emul_0/inst/i_or_ddr]
set_property PACKAGE_PIN J21 [get_ports adcorp]
set_property PACKAGE_PIN J22 [get_ports adcorn]
set_property IOSTANDARD LVDS_25 [get_ports adcorp]

set_property IOSTANDARD LVCMOS25 [get_ports {JA4[0]}]
set_property PACKAGE_PIN AA9 [get_ports {JA4[0]}]
